# Generated by Django 5.1.5 on 2025-02-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
